version: "3.4"

networks:
  default:
    external: true
    name: gocity-database_gocity
    
services:

  app:
    build:
      dockerfile: ./Dockerfile.prod
      context: ./
      network: host
    image: gocity-product-management-prod:latest
    restart: always
    ports:
      - 3000:80
